### ISSUE TITLE
[MOD] Extra Origins

### ISSUE THREAD

**Issue by Nick-McKay** [mahjerion/Craft-to-Exile-Harmony#63]
**Link the Mod's CurseForge page**
Paste the link here.
https://www.curseforge.com/minecraft/mc-mods/extra-origins

**Why you think it might be beneficial to Craft to Exile**
A clear and concise explanation of your reasons.

It adds some incredibly unique and fun origins to the mix.

**Additional context**

**Comment by mahjerion** [comment]
Hey, thanks for the suggestion. I actually am opposed to this one because I don't use origins for the unique animal-like origins. I wanted to customize it to stay true to PoE ascendancies. It was originally just a neat afterthought. Plus you dont really need this mod if you want to customize origins more - it's all datapacks :D
